version: "3.9"

services:
  webserver:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - mynetwork
    depends_on:
      - database

  database:
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - mynetwork
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=new_db
      - MYSQL_USER=dev_db
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    command: --default-authentication-plugin=mysql_native_password

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/28
